- name: Install cert-manager CRDs
  command: "/var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml apply -f https://github.com/cert-manager/cert-manager/releases/download/{{ cert_version }}/cert-manager.crds.yaml"              
  vars:
    cert_version: v1.13.2
  ignore_errors: yes  

- name: Add Jetstack Helm repository
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Update Helm repository cache
  command: helm repo update
  
# - name: Install cert-manager Helm chart  
#   kubernetes.core.helm:
#     name: cert-manager
#     chart_ref: jetstack/cert-manager
#     namespace: cert-manager
#     create_namespace: yes  
#   environment:
#     KUBECONFIG: /etc/rancher/rke2/rke2.yaml  
