---
# tasks/main.yml
- name: Include aliases tasks  
  ansible.builtin.include_tasks: aliases.yml

- name: Install heml
  ansible.builtin.include_tasks: helm-manager.yml

- name: Install cert-manager
  ansible.builtin.include_tasks: cert-manager.yml
  when: rke2_type == 'server'

- name: Install rancher-ui
  ansible.builtin.include_tasks: csak-rancher-ui.yml
  when: rke2_type == 'server'
